version: '3.1'
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306"
    networks:
      gogs:
        aliases:
          - db
    volumes:
      - "gogs-db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "gogs"
      MYSQL_DATABASE: "gogs_new"
      MYSQL_USER: "gogs"
      MYSQL_PASSWORD: "gogs"

  webapp:
    image: gogs/gogs:latest
    restart: always
    ports:
      - "10022:22"
      - "3000:3000"
    links:
      - "db:database"
    networks:
      gogs:
        aliases:
          - webapp    
    environment:
      RUN_CROND: "true"
    volumes:
      - "gogs:/data"
    depends_on:
      - db

networks:
  gogs:

volumes:
  gogs:
    driver: local
  gogs-db:
    driver: local
