version: '2'
services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    networks:
      - rocketchat
    volumes:
      - rocketchat:/data
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    depends_on:
      - mongo
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: localhost"
  
  mongo:
     image: mongo:3.2 
     restart: unless-stopped
     networks:
       - rocketchat
     volumes: 
       - rocketchat-db:/data/d
     command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1 
     labels: 
       - "traefik.enable=false"
     
  mongo-init-replica:
     image: mongo:3.2
     networks:
       - rocketchat
     command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"' 
     depends_on: 
       - mongo

networks:
  rocketchat:

volumes:
  rocketchat:
  rocketchat-db:
